### ISSUE TITLE
iptables for locking internet connection during study time

### ISSUE THREAD

**Issue by jbarciv** [MiquelEspinosa/BTime#1]
Hi there,

I'm a inexperience python programmer, so **I just want to explain an idea about a new feature that will be really awesome on BTime**.
_Have you ever thought about being lost in the desert without internet... so you only can think and meditate about life?_ In this situation, you will not waste time on WhatsApps, Instagram, Telegram and many other platforms that make us dedicate and in many cases lose time in our life. When we don't have those distractions we can fully focus on what we have at hand, and in that way, be much more productive and orderly. **Looking at the internet every two by three is not typical of Christian students.**

I discovered BTime a few weeks ago and since then my study hours have only increased. **Now a functionality about blocking the internet in the hours assigned to study would be great.** Thanks miquel-espinosa wherever you are.
God bless you

**Comment by miquel-espinosa** [comment]
Hey!

Hope you are well.
I have implemented the feature requested. Hope you find it useful.
To enable and disable, simple use `btime wifioff` and `btime wifion`.
Make sure you `git pull` to see changes reflected.
Use it wisely and I hope it helps you make the most of your time.

Best wishes.
